name: "archiver"

services:
  broker:
    container_name: "valkey"
    image: "valkey/valkey"
    restart: unless-stopped
    command:
      - "--requirepass 8f6dc2418040a6b36d60ffdc519ff85b32f3027f8d487517eed23669b93b2250"
    networks:
      archiver-net:
        ipv4_address: 172.18.0.2
  worker:
    container_name: "archiver-worker"
    image: "archiver-worker:latest"
    build:
      dockerfile: "./Worker.Dockerfile"
    environment:
      REDIS_URL: "redis://:8f6dc2418040a6b36d60ffdc519ff85b32f3027f8d487517eed23669b93b2250@172.18.0.2:6379/0"
      ARCHIVES_DIR: "/archives"
    volumes:
      - "./archives:/archives"
    restart: unless-stopped
    networks:
      archiver-net:
        ipv4_address: 172.18.0.3
  api:
    container_name: "archiver-api"
    image: "archiver-api:latest"
    build:
      dockerfile: "./Api.Dockerfile"
    environment:
      ARCHIVES_DIR: "/archives"
      REDIS_URL: "redis://:8f6dc2418040a6b36d60ffdc519ff85b32f3027f8d487517eed23669b93b2250@172.18.0.2:6379/0"
    volumes:
      - "./archives:/archives"
    restart: unless-stopped
    networks:
      archiver-net:
        ipv4_address: 172.18.0.4

networks:
  archiver-net:
    name: "archiver-net"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24